/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

version = "0.0.2-SNAPSHOT"
val keycloakVersion: String by rootProject.extra


dependencies {
    compileOnly("org.keycloak:keycloak-model-jpa:${keycloakVersion}")
    compileOnly("org.postgresql:postgresql:42.7.1")
    implementation("org.jboss.arquillian:arquillian-bom:1.1.13.Final")

//    implementation("org.keycloak:keycloak-server-spi-private:24.0.1")

//    implementation("eu.bitwalker:UserAgentUtils:1.21")

    implementation("io.jsonwebtoken:jjwt-api:0.12.5")
    runtimeOnly("io.jsonwebtoken:jjwt-gson:0.12.5")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.12.5")

    implementation("org.springframework.security:spring-security-crypto:6.3.1")

    compileOnly(files("../lib/UserAgentUtils-1.21.jar"))
    implementation("org.keycloak:keycloak-quarkus-server:${keycloakVersion}")

    testCompileOnly("org.jboss.arquillian.container:arquillian-glassfish-embedded-3.1:1.0.0.Final")
    testCompileOnly("org.jboss.arquillian.graphene:graphene-webdriver:2.5.4")
    testCompileOnly("javax.xml.bind:jaxb-api:2.3.1")
    testCompileOnly("junit:junit:4.12")
    testCompileOnly("org.keycloak:keycloak-test-helper:${keycloakVersion}")

}

//configurations.implementation.get().isCanBeResolved = true

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<Jar> {
    destinationDirectory.set(File("../build/libs"))
}